name: Deploy Spring Boot to Elastic Beanstalk

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  APPLICATION_NAME: miracle-ebs-java
  ENVIRONMENT_NAME: Miracle-ebs-java-env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      # Build Spring Boot app
      - name: Build with Maven
        run: mvn clean package

      # Prepare deployment bundle
      - name: Create deployment package
        run: |
          mkdir deploy
          cp target/*.jar deploy/application.jar
          cd deploy
          zip -r deploy.zip .

      # Authenticate to AWS using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::501789774890:role/{{secrets.ROLE_TO_ASSUME}}
          aws-region: ${{ env.AWS_REGION }}

      # Upload ZIP to S3
      - name: Upload to S3
        run: |
          aws s3 cp deploy/deploy.zip \
          s3://${{ secrets.S3_BUCKET }}/deploy-${{ github.sha }}.zip

      # Create Elastic Beanstalk version
      - name: Create EB Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.APPLICATION_NAME }} \
            --version-label version-${{ github.sha }} \
            --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="deploy-${{ github.sha }}.zip"

      # Deploy new version
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ env.ENVIRONMENT_NAME }} \
            --version-label version-${{ github.sha }}